### ISSUE TITLE
Tutorial 1 - problems with mesh

### ISSUE THREAD

**Issue by musically-impaired** [Universite-Gustave-Eiffel/I-Simpa#381]
Hello,

I'm newbie in I-SIMPA and in room acoustics modeling. I tried to follow tutorial 1, but I couldn't get proper results. So after some time I just opened tutorial1.proj file from I-SIMPA catalogue and without any changes just run calculations with "classic theory" algorithm. And these are results I've received:
 
![I-SIMPA ScrSht 01](https://github.com/Universite-Gustave-Eiffel/I-Simpa/assets/167625738/c9163609-c7e5-4342-9bb1-a1d29ca6e17e)

I've also downloaded TP_reverberant_room and my results are similar:

![image](https://github.com/Universite-Gustave-Eiffel/I-Simpa/assets/167625738/51286940-8c03-438b-bc76-38af71b20801)

As you can see sound rays are reflecting from non-existent surfaces and the calculation doesn't resemble that from tutorial. In the second project they're not even coming from any of the sound sources Why? Can anybody help me? What can I do to fix it?

I use Win 10 Pro 10.0.19045, I-SIMPA v. 1.3.4 built on 2020-12-23T16:57:21.

Thank you in advance.

**Comment by nicolas-f** [comment]
Hello,

The two screenshots in your issue is the preview of the tetgen mesh. You can hide the preview with this button 
![image](https://github.com/Universite-Gustave-Eiffel/I-Simpa/assets/1382241/80619689-547d-4b5f-9f71-80feb408db81)

https://i-simpa-wiki.readthedocs.io/fr/latest/toolbars.html#toolbar-meshing

In the tutorial you have to run spps:

https://i-simpa-wiki.readthedocs.io/fr/latest/tutorial_teaching_room.html#spps-code
